# Generated by Django 5.2.4 on 2025-09-30 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_fund_manager_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='fund_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
